### ISSUE TITLE
Thank you very much!

### ISSUE THREAD

**Issue by Shadowfita** [undrash/next.js-api-middleware#1]
I just wanted to say thank you so very much for this library and medium article. 

I've been struggling with implementing NTLM authentication within NextJS, and with your middleware on API routes I've been able to implement the express-ntlm library within my NextJS project with minimal changes to the libraries source code.

Thanks heaps.

**Comment by undrash** [comment]
Thanks @Shadowfita, I'm really glad to hear you found it useful!

**Comment by undrash** [comment]
:pray:
